### ISSUE TITLE
Documentation lacks docker compose definition

### ISSUE THREAD

**Issue by michaesc** [requarks/wiki-update-companion#3]
## Context
Docker containers can be created and started in several ways:

- $ docker run
- $ docker create
- $ docker start
- $ docker compose

## Problem
Because I'm using _docker-compose_ to create and start my WikiJS container(s) I want to include in the _compose.yml_ file the definition for a separate **wiki-update-companion container**, but there is no documentation or guidance on how to do this.

## Solution
Please describe the lines needed in a compose.yml file to properly define a new **wiki-update-companion** container.

## Proposal
Maybe this text describes a way to include the wiki-update-companion container in an existing Docker compose specification? Save the following in a file called **compose.yml** and run `docker compose up`.

```
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: wikidb
      POSTGRES_PASSWORD: whatagreatpasswd1234
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: whatagreatpasswd1234
      DB_NAME: wikidb
      UPGRADE_COMPANION: 1
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"

  wiki-update-companion:
    image: ghcr.io/requarks/wiki-update-companion:latest
    depends_on:
      - wiki
    restart: unless-stopped
    hostname: wiki-update-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  db-data:
```
